services:
  - type: web
    name: nexlink
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn nexlink_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexlink-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "nextlink.onrender.com"
      - key: REDIS_URL
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "True"
